import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen flex-col bg-black text-white">
          <UserProvider>
            <CartProvider>
              <Navbar />

              {/* 🔧 Add this main wrapper with flex-1 */}
              <main className="flex-1">{children}</main>

              <Footer />
            </CartProvider>
          </UserProvider>

          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}


